<?php
/**
 * APIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialDocument
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Material Documents - Read, Create
 *
 * This service enables you to retrieve and create material documents, for example, to post a goods receipt for a purchase order or to document the transfer of materials between two storage locations. Additionally, the service allows you to cancel existing material documents or single items. It can be consumed by external systems and user interfaces.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BeLenka\SAP\MaterialDocument\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * APIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeTest Class Doc Comment
 *
 * @category    Class
 * @description APIMATERIALDOCUMENTSRVAMaterialDocumentItemType
 * @package     BeLenka\SAP\MaterialDocument
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "APIMATERIALDOCUMENTSRVAMaterialDocumentItemType"
     */
    public function testAPIMATERIALDOCUMENTSRVAMaterialDocumentItemType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document_year"
     */
    public function testPropertyMaterialDocumentYear()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document"
     */
    public function testPropertyMaterialDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document_item"
     */
    public function testPropertyMaterialDocumentItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material"
     */
    public function testPropertyMaterial()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "plant"
     */
    public function testPropertyPlant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "storage_location"
     */
    public function testPropertyStorageLocation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "batch"
     */
    public function testPropertyBatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "goods_movement_type"
     */
    public function testPropertyGoodsMovementType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inventory_stock_type"
     */
    public function testPropertyInventoryStockType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inventory_valuation_type"
     */
    public function testPropertyInventoryValuationType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inventory_special_stock_type"
     */
    public function testPropertyInventorySpecialStockType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "supplier"
     */
    public function testPropertySupplier()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "customer"
     */
    public function testPropertyCustomer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sales_order"
     */
    public function testPropertySalesOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sales_order_item"
     */
    public function testPropertySalesOrderItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sales_order_schedule_line"
     */
    public function testPropertySalesOrderScheduleLine()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "purchase_order"
     */
    public function testPropertyPurchaseOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "purchase_order_item"
     */
    public function testPropertyPurchaseOrderItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "wbs_element"
     */
    public function testPropertyWbsElement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manufacturing_order"
     */
    public function testPropertyManufacturingOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manufacturing_order_item"
     */
    public function testPropertyManufacturingOrderItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "goods_movement_ref_doc_type"
     */
    public function testPropertyGoodsMovementRefDocType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "goods_movement_reason_code"
     */
    public function testPropertyGoodsMovementReasonCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery"
     */
    public function testPropertyDelivery()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "delivery_item"
     */
    public function testPropertyDeliveryItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "account_assignment_category"
     */
    public function testPropertyAccountAssignmentCategory()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_center"
     */
    public function testPropertyCostCenter()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "controlling_area"
     */
    public function testPropertyControllingArea()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cost_object"
     */
    public function testPropertyCostObject()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gl_account"
     */
    public function testPropertyGlAccount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "functional_area"
     */
    public function testPropertyFunctionalArea()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "profitability_segment"
     */
    public function testPropertyProfitabilitySegment()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "profit_center"
     */
    public function testPropertyProfitCenter()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "master_fixed_asset"
     */
    public function testPropertyMasterFixedAsset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fixed_asset"
     */
    public function testPropertyFixedAsset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_base_unit"
     */
    public function testPropertyMaterialBaseUnit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity_in_base_unit"
     */
    public function testPropertyQuantityInBaseUnit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "entry_unit"
     */
    public function testPropertyEntryUnit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity_in_entry_unit"
     */
    public function testPropertyQuantityInEntryUnit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "company_code_currency"
     */
    public function testPropertyCompanyCodeCurrency()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "gds_mvt_ext_amt_in_co_code_crcy"
     */
    public function testPropertyGdsMvtExtAmtInCoCodeCrcy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sls_prc_amt_incl_vatin_co_code_crcy"
     */
    public function testPropertySlsPrcAmtInclVatinCoCodeCrcy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fiscal_year"
     */
    public function testPropertyFiscalYear()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fiscal_year_period"
     */
    public function testPropertyFiscalYearPeriod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fiscal_year_variant"
     */
    public function testPropertyFiscalYearVariant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issg_or_rcvg_material"
     */
    public function testPropertyIssgOrRcvgMaterial()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issg_or_rcvg_batch"
     */
    public function testPropertyIssgOrRcvgBatch()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issuing_or_receiving_plant"
     */
    public function testPropertyIssuingOrReceivingPlant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issuing_or_receiving_storage_loc"
     */
    public function testPropertyIssuingOrReceivingStorageLoc()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issuing_or_receiving_stock_type"
     */
    public function testPropertyIssuingOrReceivingStockType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issg_or_rcvg_spcl_stock_ind"
     */
    public function testPropertyIssgOrRcvgSpclStockInd()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "issuing_or_receiving_val_type"
     */
    public function testPropertyIssuingOrReceivingValType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_completely_delivered"
     */
    public function testPropertyIsCompletelyDelivered()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document_item_text"
     */
    public function testPropertyMaterialDocumentItemText()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "goods_recipient_name"
     */
    public function testPropertyGoodsRecipientName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "unloading_point_name"
     */
    public function testPropertyUnloadingPointName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shelf_life_expiration_date"
     */
    public function testPropertyShelfLifeExpirationDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manufacture_date"
     */
    public function testPropertyManufactureDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "serial_numbers_are_created_automly"
     */
    public function testPropertySerialNumbersAreCreatedAutomly()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reservation"
     */
    public function testPropertyReservation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reservation_item"
     */
    public function testPropertyReservationItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reservation_item_record_type"
     */
    public function testPropertyReservationItemRecordType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reservation_is_finally_issued"
     */
    public function testPropertyReservationIsFinallyIssued()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "special_stock_idfg_sales_order"
     */
    public function testPropertySpecialStockIdfgSalesOrder()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "special_stock_idfg_sales_order_item"
     */
    public function testPropertySpecialStockIdfgSalesOrderItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "special_stock_idfg_wbs_element"
     */
    public function testPropertySpecialStockIdfgWbsElement()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "is_automatically_created"
     */
    public function testPropertyIsAutomaticallyCreated()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document_line"
     */
    public function testPropertyMaterialDocumentLine()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document_parent_line"
     */
    public function testPropertyMaterialDocumentParentLine()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "hierarchy_node_level"
     */
    public function testPropertyHierarchyNodeLevel()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "goods_movement_is_cancelled"
     */
    public function testPropertyGoodsMovementIsCancelled()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reversed_material_document_year"
     */
    public function testPropertyReversedMaterialDocumentYear()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reversed_material_document"
     */
    public function testPropertyReversedMaterialDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reversed_material_document_item"
     */
    public function testPropertyReversedMaterialDocumentItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reference_document_fiscal_year"
     */
    public function testPropertyReferenceDocumentFiscalYear()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invtry_mgmt_ref_document_item"
     */
    public function testPropertyInvtryMgmtRefDocumentItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "invtry_mgmt_reference_document"
     */
    public function testPropertyInvtryMgmtReferenceDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document_posting_type"
     */
    public function testPropertyMaterialDocumentPostingType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inventory_usability_code"
     */
    public function testPropertyInventoryUsabilityCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ewm_warehouse"
     */
    public function testPropertyEwmWarehouse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ewm_storage_bin"
     */
    public function testPropertyEwmStorageBin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "debit_credit_code"
     */
    public function testPropertyDebitCreditCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_material_document_header"
     */
    public function testPropertyToMaterialDocumentHeader()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_serial_numbers"
     */
    public function testPropertyToSerialNumbers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
