<?php
/**
 * APIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeCreateToSerialNumbersTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialDocument
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Material Documents - Read, Create
 *
 * This service enables you to retrieve and create material documents, for example, to post a goods receipt for a purchase order or to document the transfer of materials between two storage locations. Additionally, the service allows you to cancel existing material documents or single items. It can be consumed by external systems and user interfaces.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BeLenka\SAP\MaterialDocument\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * APIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeCreateToSerialNumbersTest Class Doc Comment
 *
 * @category    Class
 * @description APIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeCreateToSerialNumbers
 * @package     BeLenka\SAP\MaterialDocument
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeCreateToSerialNumbersTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "APIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeCreateToSerialNumbers"
     */
    public function testAPIMATERIALDOCUMENTSRVAMaterialDocumentItemTypeCreateToSerialNumbers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "results"
     */
    public function testPropertyResults()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
