<?php
/**
 * APIMATERIALDOCUMENTSRVAMaterialDocumentHeaderTypeCreateTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialDocument
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Material Documents - Read, Create
 *
 * This service enables you to retrieve and create material documents, for example, to post a goods receipt for a purchase order or to document the transfer of materials between two storage locations. Additionally, the service allows you to cancel existing material documents or single items. It can be consumed by external systems and user interfaces.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace BeLenka\SAP\MaterialDocument\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * APIMATERIALDOCUMENTSRVAMaterialDocumentHeaderTypeCreateTest Class Doc Comment
 *
 * @category    Class
 * @description APIMATERIALDOCUMENTSRVAMaterialDocumentHeaderTypeCreate
 * @package     BeLenka\SAP\MaterialDocument
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class APIMATERIALDOCUMENTSRVAMaterialDocumentHeaderTypeCreateTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "APIMATERIALDOCUMENTSRVAMaterialDocumentHeaderTypeCreate"
     */
    public function testAPIMATERIALDOCUMENTSRVAMaterialDocumentHeaderTypeCreate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document_year"
     */
    public function testPropertyMaterialDocumentYear()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document"
     */
    public function testPropertyMaterialDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "inventory_transaction_type"
     */
    public function testPropertyInventoryTransactionType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "document_date"
     */
    public function testPropertyDocumentDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "posting_date"
     */
    public function testPropertyPostingDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "creation_date"
     */
    public function testPropertyCreationDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "creation_time"
     */
    public function testPropertyCreationTime()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "created_by_user"
     */
    public function testPropertyCreatedByUser()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "material_document_header_text"
     */
    public function testPropertyMaterialDocumentHeaderText()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "reference_document"
     */
    public function testPropertyReferenceDocument()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "version_for_printing_slip"
     */
    public function testPropertyVersionForPrintingSlip()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "manual_print_is_triggered"
     */
    public function testPropertyManualPrintIsTriggered()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "ctrl_postg_for_ext_whse_mgmt_syst"
     */
    public function testPropertyCtrlPostgForExtWhseMgmtSyst()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "goods_movement_code"
     */
    public function testPropertyGoodsMovementCode()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "to_material_document_item"
     */
    public function testPropertyToMaterialDocumentItem()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
