<?php
/**
 * DocumentItemsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialDocument
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Material Documents - Read, Create
 *
 * This service enables you to retrieve and create material documents, for example, to post a goods receipt for a purchase order or to document the transfer of materials between two storage locations. Additionally, the service allows you to cancel existing material documents or single items. It can be consumed by external systems and user interfaces.
 *
 * The version of the OpenAPI document: 1.3.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\SAP\MaterialDocument\Test\Api;

use \BeLenka\SAP\MaterialDocument\Configuration;
use \BeLenka\SAP\MaterialDocument\ApiException;
use \BeLenka\SAP\MaterialDocument\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * DocumentItemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\SAP\MaterialDocument
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentItemsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for aMaterialDocumentHeaderMaterialDocumentYearMaterialDocumentYearMaterialDocumentMaterialDocumentToMaterialDocumentItemGet
     *
     * Reads information for a specific material document header and material document items.
     *
     */
    public function testAMaterialDocumentHeaderMaterialDocumentYearMaterialDocumentYearMaterialDocumentMaterialDocumentToMaterialDocumentItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aMaterialDocumentItemGet
     *
     * Reads information on material document items level.
     *
     */
    public function testAMaterialDocumentItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aMaterialDocumentItemMaterialDocumentYearMaterialDocumentYearMaterialDocumentMaterialDocumentMaterialDocumentItemMaterialDocumentItemGet
     *
     * Reads information on material document items level for a specific material document.
     *
     */
    public function testAMaterialDocumentItemMaterialDocumentYearMaterialDocumentYearMaterialDocumentMaterialDocumentMaterialDocumentItemMaterialDocumentItemGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aMaterialDocumentItemMaterialDocumentYearMaterialDocumentYearMaterialDocumentMaterialDocumentMaterialDocumentItemMaterialDocumentItemToMaterialDocumentHeaderGet
     *
     * Reads information on material document item and header level for a specific material document item.
     *
     */
    public function testAMaterialDocumentItemMaterialDocumentYearMaterialDocumentYearMaterialDocumentMaterialDocumentMaterialDocumentItemMaterialDocumentItemToMaterialDocumentHeaderGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for aMaterialDocumentItemMaterialDocumentYearMaterialDocumentYearMaterialDocumentMaterialDocumentMaterialDocumentItemMaterialDocumentItemToSerialNumbersGet
     *
     * Reads information on serial numbers for a specific material document item.
     *
     */
    public function testAMaterialDocumentItemMaterialDocumentYearMaterialDocumentYearMaterialDocumentMaterialDocumentMaterialDocumentItemMaterialDocumentItemToSerialNumbersGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for cancelItemPost
     *
     * Cancels a material document item.
     *
     */
    public function testCancelItemPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
